name: Email Action Test

on:
  workflow_dispatch:  # manual trigger

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 23f2003050@ds.study.iitm.ac.in
        run: echo "Hello, world!"
